import HomeSection from '../sections/Home/index/Home';
import PositionSection from '../sections/Position/index/Position';
import BlogSection from '../sections/Blog/index/Blog';
import PostcardSection from '../sections/Postcard/index/Postcard';
import PodcastsSection from '../sections/Podcasts/index/Podcasts';
import BooksSection from '../sections/Books/index/Books';
import BoardSection from '../sections/Board/index/Board';
import WeatherSection from '../sections/Weather/index/Weather';
import PostsSection from '../sections/Posts/index/Posts';
import WidgetsSection from '../sections/Widgets/index/Widgets';
import NoMatchSection from '../sections/NoMatch/index/NoMatch';

export const Home = HomeSection;
export const Position = PositionSection;
export const Blog = BlogSection;
export const Postcard = PostcardSection;
export const Podcasts = PodcastsSection;
export const Books = BooksSection;
export const Board = BoardSection;
export const Weather = WeatherSection;
export const Posts = PostsSection;
export const Widgets = WidgetsSection;
export const NoMatch = NoMatchSection;
