export const FETCH_BLOG_POSTS = 'FETCH_BLOG_POSTS';
export const ERROR_FETCHING_BLOG_POSTS = 'ERROR_FETCHING_BLOG_POSTS';
export const BLOG_USER_SELECTED = 'BLOG_USER_SELECTED';
export const PODCAST_SELECTED = 'PODCAST_SELECTED';
