import APortraitOfTheArtistAsAYoungMan from '../../../assets/images/covers/cover1.jpg';
import BraveNewWorld from '../../../assets/images/covers/cover2.jpg';
import Catch22 from '../../../assets/images/covers/cover3.jpg';
import DarknessAtNoon from '../../../assets/images/covers/cover4.jpg';
import Lolita from '../../../assets/images/covers/cover5.jpg';
import NineteenEightyFourANovel from '../../../assets/images/covers/cover6.jpg';
import SlaughterhouseFive from '../../../assets/images/covers/cover7.jpg';
import SonsAndLovers from '../../../assets/images/covers/cover8.jpg';
import TheGrapesOfWrath from '../../../assets/images/covers/cover9.jpg';
import TheGreatGatsby from '../../../assets/images/covers/cover10.jpg';
import TheSoundAndTheFury from '../../../assets/images/covers/cover11.jpg';
import Ulysses from '../../../assets/images/covers/cover12.jpg';

export default [
  {
    id: '9020a324-5b64-4056-af1c-7a4a922b5e72',
    title: 'Ulysses',
    author: 'James Joyce',
    year: 1922,
    genre: 'Modernist novel',
    publisher: 'Sylvia Beach',
    pages: 730,
    cover: 'cover12.jpg',
    image: Ulysses,
  },
  {
    id: '6f7587e5-7449-484f-98b0-1d28dfca2ef9',
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    year: 1925,
    genre: 'Tragedy',
    publisher: "Charles Scribner's Sons",
    pages: 218,
    cover: 'cover10.jpg',
    image: TheGreatGatsby,
  },
  {
    id: 'c8a1abf3-60e3-44d9-a630-81c717c5814c',
    title: 'A Portrait of the Artist as a Young Man',
    author: 'James Joyce',
    year: 1916,
    genre: 'Modernism',
    publisher: 'B. W. Huebsch',
    pages: 299,
    cover: 'cover1.jpg',
    image: APortraitOfTheArtistAsAYoungMan,
  },
  {
    id: 'a2ce04ef-2c62-4996-b3d8-b13a8441770d',
    title: 'Lolita',
    author: 'Vladimir Nabokov',
    year: 1955,
    genre: 'Novel',
    publisher: 'Olympia Press',
    pages: 336,
    cover: 'cover5.jpg',
    image: Lolita,
  },
  {
    id: 'bd20e6ce-292c-48a2-88f4-b19e7d588b92',
    title: 'Brave New World',
    author: 'Aldous Huxley',
    year: 1932,
    genre: 'Dystopian fiction',
    publisher: 'Chatto & Windus',
    pages: 311,
    cover: 'cover2.jpg',
    image: BraveNewWorld,
  },
  {
    id: 'b39f923c-a111-4f5c-9ae6-17a29a27c236',
    title: 'The Sound and the Fury',
    author: 'William Faulkner',
    year: 1929,
    genre: 'Modernist novel',
    publisher: 'J. Cape and H. Smith',
    pages: 326,
    cover: 'cover11.jpg',
    image: TheSoundAndTheFury,
  },
  {
    id: 'cef99171-4d4a-48a4-bf70-ab4e26e4ba86',
    title: 'Catch-22',
    author: 'Joseph Heller',
    year: 1961,
    genre: 'Satire',
    publisher: 'Simon & Schuster',
    pages: 453,
    cover: 'cover3.jpg',
    image: Catch22,
  },
  {
    id: '3578f03d-02f7-40df-af90-6df83a2f2ba9',
    title: 'Darkness at Noon',
    author: 'Arthur Koestler',
    year: 1940,
    genre: 'Novel',
    publisher: 'Macmillan',
    pages: 254,
    cover: 'cover4.jpg',
    image: DarknessAtNoon,
  },
  {
    id: '5c9ecd8f-5460-41dd-9195-b4256738bfbe',
    title: 'Sons and Lovers',
    author: 'D. H. Lawrence',
    year: 1913,
    genre: 'Autobiographical novel',
    publisher: 'G. Duckworth and Co. Ltd',
    pages: 423,
    cover: 'cover8.jpg',
    image: SonsAndLovers,
  },
  {
    id: 'a93fb518-02f2-4b66-9cd2-6ba436d38dfc',
    title: 'The Grapes of Wrath',
    author: 'John Steinbeck',
    year: 1939,
    genre: 'Novel',
    publisher: 'The Viking Press-J. Lloyd',
    pages: 464,
    cover: 'cover9.jpg',
    image: TheGrapesOfWrath,
  },
  {
    id: '89357486-a7d7-4bdc-86b4-183098d23080',
    title: '1984',
    author: 'George Orwell',
    year: 1949,
    genre: 'Dystopian',
    publisher: 'Secker & Warburg',
    pages: 328,
    cover: 'cover6.jpg',
    image: NineteenEightyFourANovel,
  },
  {
    id: 'e46e79f2-c73c-498c-968c-0eed08632cc8',
    title: 'Slaughterhouse-Five',
    author: 'Kurt Vonnegut',
    year: 1969,
    genre: 'Science fiction',
    publisher: 'Delacorte',
    pages: 385,
    cover: 'cover7.jpg',
    image: SlaughterhouseFive,
  },
];
