// blog section
export const BLOG_POSTS_FETCH_REQUEST = 'BLOG_POSTS_FETCH_REQUEST';
export const BLOG_POSTS_FETCH_SUCCESS = 'BLOG_POSTS_FETCH_SUCCESS';
export const BLOG_POSTS_FETCH_FAILURE = 'BLOG_POSTS_FETCH_FAILURE';
export const BLOG_USER_SELECTED = 'BLOG_USER_SELECTED';

// podcast section
export const PODCASTS_ITEM_SELECTED = 'PODCASTS_ITEM_SELECTED';

// book section
export const BOOKS_ITEM_SELECTED = 'BOOKS_ITEM_SELECTED';
export const BOOKS_VIEW_CHANGED = 'BOOKS_VIEW_CHANGED';
export const BOOKS_SEARCH_REQUEST = 'BOOKS_SEARCH_REQUEST';

// weather section
export const WEATHER_FORECASTS_FETCH_REQUEST = 'WEATHER_FORECASTS_FETCH_REQUEST';
export const WEATHER_FORECASTS_FETCH_SUCCESS = 'WEATHER_FORECASTS_FETCH_SUCCESS';
export const WEATHER_FORECASTS_FETCH_FAILURE = 'WEATHER_FORECASTS_FETCH_FAILURE';
export const WEATHER_FORECASTS_DELETE = 'WEATHER_FORECASTS_DELETE';
export const WEATHER_FORECASTS_ERROR_HIDE = 'WEATHER_FORECASTS_ERROR_HIDE';
export const WEATHER_FORECASTS_VIEW_CHANGED = 'WEATHER_FORECASTS_VIEW_CHANGED';
export const WEATHER_CITY_SELECTED = 'WEATHER_CITY_SELECTED';
export const WEATHER_MOUNT_MAP_SUCCESS = 'WEATHER_MOUNT_MAP_SUCCESS';
export const WEATHER_MOUNT_MAP_FAILURE = 'WEATHER_MOUNT_MAP_FAILURE';

// modal
export const MODAL_OPEN = 'MODAL_OPEN';
export const MODAL_CLOSE = 'MODAL_CLOSE';

// posts section
export const POSTS_LIST_REQUEST = 'POSTS_LIST_REQUEST';
export const POSTS_LIST_SUCCESS = 'POSTS_LIST_SUCCESS';
export const POSTS_LIST_FAILURE = 'POSTS_LIST_FAILURE';
export const POSTS_ADDING_REQUEST = 'POSTS_ADDING_REQUEST';
export const POSTS_ADDING_SUCCESS = 'POSTS_ADDING_SUCCESS';
export const POSTS_MESSAGE_ADD = 'POSTS_MESSAGE_ADD';
export const POSTS_ADDING_FAILURE = 'POSTS_ADDING_FAILURE';
export const POSTS_REMOVING_REQUEST = 'POSTS_REMOVING_REQUEST';
export const POSTS_REMOVING_FAILURE = 'POSTS_REMOVING_FAILURE';
export const POSTS_REMOVING_ASK = 'POSTS_REMOVING_ASK';
export const POSTS_REMOVING_RESET = 'POSTS_REMOVING_RESET';
export const POSTS_ADDING_RESET = 'POSTS_ADDING_RESET';
export const POSTS_MESSAGE_REMOVE = 'POSTS_MESSAGE_REMOVE';
export const POSTS_REMOVE_ITEM = 'POSTS_REMOVE_ITEM';
export const POSTS_REMOVING_SUCCESS = 'POSTS_REMOVING_SUCCESS';
export const POSTS_READING_RESET = 'POSTS_READING_RESET';
export const POSTS_SEARCH_REQUEST = 'POSTS_SEARCH_REQUEST';
