export const FETCH_BLOG_POSTS = 'FETCH_BLOG_POSTS';
export const ERROR_FETCHING_BLOG_POSTS = 'ERROR_FETCHING_BLOG_POSTS';
export const BLOG_USER_SELECTED = 'BLOG_USER_SELECTED';
export const PODCAST_SELECTED = 'PODCAST_SELECTED';
export const SET_ACTIVE_BOOK = 'SET_ACTIVE_BOOK';
export const SET_BOOKS_VIEW = 'SET_BOOKS_VIEW';
export const BOOK_SEARCH = 'BOOK_SEARCH';
